---
- name: Install autojump
  become: yes
  apt:
    name: autojump
    state: present
- name: Append autojump into bashrc
  lineinfile:
    path: "{{ workspace_setup_home }}/.bashrc"
    line: . /usr/share/autojump/autojump.sh
    regexp: .*autojump.sh
    state: present
