---
- name: "Gather machine facts"
  setup:
- name: Update apt caches
  become: yes
  apt:
    update_cache: yes
- import_tasks: dependencies.yml
- import_tasks: autojump.yml
- import_tasks: history.yml
- import_tasks: starship.yml
- import_tasks: vim.yml
- import_tasks: python.yml
- import_tasks: mise.yml
- import_tasks: rust.yml
- import_tasks: nodejs.yml
