---
- name: Check if nvm exists
  stat:
    path: "{{ ansible_env.HOME }}/.nvm"
  register: nvm_dir

- name: Remove nvm
  block:
    - name: Unload nvm
      shell: |
        set -euo pipefail
        nvm unload || true
      args:
        executable: /bin/bash

    - name: Remove nvm directory
      file:
        path: "{{ ansible_env.HOME }}/.nvm"
        state: absent

    - name: Remove nvm lines from .bashrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "{{ item }}"
        state: absent
      loop:
        - 'export NVM_DIR="$HOME/.nvm"'
        - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm'
        - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion'
  when: nvm_dir.stat.exists

- name: Install Node.js LTS via mise
  shell: |
    set -euo pipefail
    {{ ansible_env.HOME }}/.local/bin/mise use --global node@lts
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.local/share/mise/installs/node"
