---
- name: Install Node.js LTS via mise
  shell: |
    set -euo pipefail
    eval "$({{ ansible_env.HOME }}/.local/bin/mise activate bash)"
    mise use --global node@lts
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.local/share/mise/installs/node"
