---
- name: Install Rust latest via mise
  shell: |
    set -euo pipefail
    eval "$({{ ansible_env.HOME }}/.local/bin/mise activate bash)"
    mise use --global rust@latest
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.local/share/mise/installs/rust"
