---
- name: Check if uv is available
  command: which uv
  register: uv_check
  changed_when: false
  failed_when: false

- name: Install uv (Astral) for current user
  shell: |
    curl -LsSf https://astral.sh/uv/install.sh | sh
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/uv"
  when: uv_check.rc != 0
