---
- name: Verify
  hosts: all
  tasks:
  - name: assert command version
    include_role:
      name: assert_shell_command
    vars:
      command: "{{ item }}"
    with_items:
      - python3 --version
      - pip --version
      - vim --version
      - mise --version
      - node --version
      - rustc --version
      - starship --version
